# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-21 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_name', models.CharField(default='N/A', max_length=30)),
                ('issue_model', models.CharField(default='N/A', max_length=30)),
                ('issue_count', models.IntegerField(default=0)),
                ('isuue_to', models.CharField(default='N/A', max_length=50)),
                ('issue_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Issues',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='N/A', max_length=30)),
                ('item_model', models.CharField(default='N/A', max_length=30)),
                ('item_cost', models.IntegerField(default=0)),
                ('item_count', models.IntegerField(default=-1)),
                ('item_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(default='N/A', max_length=30)),
                ('stock_model', models.CharField(default='N/A', max_length=30)),
                ('stock_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Stocks',
            },
        ),
    ]
