# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-03 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyPin_View', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issued_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(default=-1)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('issued_quantity', models.IntegerField(default=0)),
                ('issued_to', models.CharField(default='N/A', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='issues',
            name='item_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='items',
            name='item_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='stocks',
            name='item_id',
            field=models.IntegerField(default=-1),
        ),
    ]
